# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: sur950.GeekCode
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.17763.0
Installers:
  - Architecture: x64
    InstallerType: exe
    InstallerUrl: https://github.com/sur950/GeekCode/releases/download/v1.0.0/geekcode-1.0.0-win-x64.exe
    InstallerSha256: REPLACE_WITH_SHA256_OF_WINDOWS_BINARY
    InstallerSwitches:
      Silent: /S
      SilentWithProgress: /S
ManifestType: installer
ManifestVersion: 1.6.0
